Taek/nerf2plenoxel
taekkii/Deblur-NeRF pull request #1
Opened 2022-11-01 08:44 UTC by taekkii

camera trajectory kernel + plenoxel initial ver.

2022-11-01 08:59 UTC, dongwoohhh commented on .gitignore
> +log/*
remove this line

2022-11-01 09:01 UTC, dongwoohhh commented on NOTE_TO_SELF.md
> +- (11/1) plenoxel에서는 첫 forward결과가 rgb 모두 0.5인데, 여기선 0.9쯤으로 찍히는 차이가 있음. 여기서 찾아봐야 할듯
Remove this file (Just keep in your local workspace)

2022-11-01 09:04 UTC, dongwoohhh commented on NeRF.py
> +        if args.plenoxel:
이 밑으로는 한글로 달게

조건문으로 할때 default setting 이 제일 위에 오는게 유지보수에 좋아
우리가 plenoxel을 수정할 수도 있으니까
```suggestion
        if args.architecture == 'nerf':

        elif args.architecture == 'plenoxel':
        
        else: 
            raise NotImplementedError
        
```

2022-11-02 02:54 UTC, taekkii commented on .gitignore
> +log/*
log가 commit되면 안되지 않나요?

2022-11-02 05:49 UTC, dongwoohhh requested changes
alexyu_svox2 ... .py
option ... .py

파일들
svox2 나 plenoxel 폴더를 만들어서 파일 이름앞에는 alexyu가 안들어가게 하고,

option파일 두개는 충돌없으면 합치는게 좋을듯

그리고 아래 코멘트한것들 고치고나면
git squash 라고 검색해서 지저분한 커밋로그들 하나로 합쳐서 다시 PR하는게 좋을 듯.

이 커밋이 체크포인트이고 다른 사람에게는 그전에 디버깅위해서 커밋 조금씩한 것들은 의미가 없어서 합쳐졌을때 햇갈리게 되니까

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +            import alexyu_svox2_llff_dataset as svox_llff
우선은
파일 이름을 alexyu_svox2_llff_dataset 이렇게 하지말고
경로를 plenoxel/svox2_llff_dataset 이런식으로 바꾸고

클래스 안에서 import 하는건 좋지 않으니까 파일 맨위로 옮기도록

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +            import json
마찬가지

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +            reso_list = json.loads(args.reso)
resolution 이 2d list형태로 되있는 것 같은데 json.loads가 꼭 필요할까?
처음부터 리스트로 받아도되고, 파이썬 빌트인에서 스트링에서 리스트로 바꾸는 법 찾아도 되고,
개인적으로는 처음 args 받을때부터 리스트로 받는게 좋을 것같음 지금은 스트링으로 받는거같은데

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +            dset = svox_llff.LLFFDataset(args.datadir,split='train',device='cuda')
현재 dset에서 사용하는게 dset.scene_center, dset.scene_radius 두개만 쓰는 거면, 기존 deblurnerf 에서 사용하는 llff dataset 파일에 해당 값들 추가하도록 바꾸는게 좋을듯 redundancy 같음

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +            #[11/1 taekkii] some missing inits on plenoxel original code.
Initialization은 크게 영향없을 것같아서 코멘트 지워도 될 것 같음

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +            import alexyu_svox2_utils
import 클래스 내에서 x

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +
띄어쓰기 한칸만

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +                        rgb, depth, acc, extras = self.render(H, W, K, chunk, rays,gt=gt,**kwargs)
rays, 뒤에 띄어쓰기

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +                if extras.get('rgb0',None) is not None:
'rgb0', 뒤에 띄어쓰기

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +                else: rgb0 = None
```suggestion
                else: 
                    rgb0 = None
```

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +                #rgb0 means coarse rgb in original nerf. plenoxel doesn't have it, so don' need to return rgb0
주석 간략하게 
"# rgb0: rgb output of coarse network."
주석쓸때 # 뒤에 한칸 띄우고

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +        #normalize (could be helpful, or not)
주석 "#" 뒤에 한칸띄우고

아래 모두 마찬가지

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +        if self.is_plenoxel():
self.is_plenoxel() 이 method가 redundant해보이는데, 
```suggestion
        args.architecture == "plenoxel":
```
이런걸로 바꿔도될듯

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +            svox2_rays = svox2.Rays(rays_o.cuda(),rays_d.cuda())
rays_o, rays_d 가 이미 cudaTensor가 아니야?
device 확인해보고 이미 cudaTensor이면 .cuda() 지우면될듯

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +
delete this line

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +            #if we have gt, do forward-backward
if문 사이에 이렇게 주석다는게 보기 편하지 않은 듯.
주석을 "# if ~" 이렇게 시작할 필요없음 
```python
if gt is None:
    # Forward-only.
    rgb_map = self.plenoxel.volume_render(svox2_rays)
else:
    # [TEMPORARY] Plenoxel style argument are forcefully applied. 
    # TODO (taekkii) reconsider arguments
    # Forward-backward.
    rgb_map = self.plenoxel.volume_render_fused(svox2_rays,gt,
        beta_loss=kwargs.get('lambda_beta',0.0),
```

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +            # Batchfy and Render and reshape
마침표

2022-11-02 05:49 UTC, dongwoohhh commented on NeRF.py
> +    def is_plenoxel(self):
redundant method

2022-11-02 05:49 UTC, dongwoohhh commented on configs/demo_blurball.txt
> +basedir = ./log/blurball_full
log -> results
no scene name after ./results
```suggestion
basedir = ./results
```

2022-11-02 05:49 UTC, dongwoohhh commented on configs/demo_blurball.txt
> +tbdir = ./log/blurball_full/tb
```suggestion
tbdir = ./results
```

2022-11-02 05:49 UTC, dongwoohhh commented on configs/demo_blurball.txt
> +reso = "[[256,256,128],[512,512,128]]"
I think it doesn't work. It gives error message

2022-11-02 05:49 UTC, dongwoohhh commented on option_plenoxel.py
> +    return parser
Add empty line

2022-11-03 02:29 UTC, taekkii commented on NeRF.py
> +        if self.is_plenoxel():
이거 arg 항상 모든 메소드에서 갖고 있는게 아니라서, 유지하는 것이 좋을 것 같습니다.

2022-11-08 04:43 UTC, dongwoohhh commented
model load weight에 버그 있음
저장을 모든 파라미터 다 하지 않거나, 로드가 다 안되거나

2022-11-10 05:40 UTC, closed without merging